# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  bucket: "connect-holiday"
  secret_key_base: "b0210184c212660ff4cfa1055793ce2df651c64f90cdc64bc89a8c4ec7c3ecfc59557d3b7c9a2d5998ada604ed0840cf8c36c3f7f7273882cff2434c5bc9d7ec"
  aws_access_key_id: "AKIAJLLHPYSA5VLLGDFQ"
  aws_secret_access_key: "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"

test:
  secret_key_base: 627ac3f8cc1126a78834018b4b3cd395ac75af28e058f5377a6599ba34756c407290b9ff6298989de7693ec7216ddca50b4bfc4eea898363c497851bca65ee24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  bucket: "connect-holiday"
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["aws_access_key_id"] %>
  aws_secret_access_key: <%= ENV["aws_secret_access_key"] %>
